<a href="https://colab.research.google.com/github/zorporate/cs510nlp/blob/main/load_imdb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

     |████████████████████████████████| 2.1MB 6.7MB/s 
     |████████████████████████████████| 3.3MB 38.1MB/s 
     |████████████████████████████████| 901kB 47.9MB/s 


# Get EWE vectors

In [ ]:
%%bash

wget -q https://www.dropbox.com/s/5egqnbktbfxp2im/ewe_uni.txt.zip?dl=0 -O ./ewe.zip
unzip -qo ewe.zip
rm -rf __MACOSX/ MACOSX/
rm ewe.zip
head ewe_uni.txt

the -0.193682283163 -0.152885451913 0.00764408055693 -0.0254001040012 -0.0527419932187 -0.258357435465 -4.13782644272 0.640544116497 0.333551675081 -0.422751069069 0.39350092411 -0.184653550386 0.133011296391 -0.0202169623226 0.382724046707 -0.558341026306 -0.111894078553 -0.00917041953653 0.313256621361 0.0723667219281 0.102137431502 -0.0789565816522 -0.0567378103733 -0.280855000019 -0.458377659321 0.26387411356 0.0766083225608 -0.0393931828439 -0.204306602478 0.00857916567475 -0.297831892967 0.173263564706 0.0584956146777 -0.271546214819 0.0923996418715 0.354975402355 0.0457001142204 -0.160491466522 0.504980742931 -0.177410885692 0.307809114456 0.100258789957 0.0420325696468 0.0769292414188 0.278610706329 0.071012288332 0.0506280511618 -0.298026770353 -0.435857564211 0.319009244442 0.392242819071 0.364684045315 0.14129075408 -0.134040102363 0.121166676283 -0.157480448484 0.360082387924 0.311951518059 -0.118711099029 0.0139132644981 0.447214573622 0.368951529264 0.122153200209 -0.4350

In [ ]:
import pandas as pd

df = pd.read_csv('ewe_uni.txt', sep = " ", header=None, index_col=0)
df.shape

(183712, 300)

In [ ]:
df.head()

1         2         3    ...       298       299       300
0                                  ...                              
the -0.193682 -0.152885  0.007644  ... -0.539710  0.212540  0.001292
and -0.080430 -0.260765 -0.330572  ... -0.364723 -0.090796  0.391755
i   -0.031085 -0.191804 -0.128438  ...  0.094401  0.103395  0.094932
to  -0.233014 -0.448184  0.051642  ...  0.052464  0.153408 -0.372703
a   -0.011401  0.793292 -0.494033  ...  0.018762 -0.310064 -0.351996

[5 rows x 300 columns]

In [ ]:
df.head().to_numpy()[0][0]

-0.193682283163

## Load EWE vectors

In [ ]:
from torchtext.vocab import Vectors

In [ ]:
vectors = Vectors('ewe_uni.txt')

100%|█████████▉| 183254/183712 [00:19<00:00, 9417.67it/s]

In [ ]:
examples = ['chip', 'baby', 'Beautiful']
vectors.get_vecs_by_tokens(examples, lower_case_backup=True)

In [ ]:
examples = ['the', 'and', 'i']
vectors.get_vecs_by_tokens(examples, lower_case_backup=True)

In [ ]:
examples = ['The']
vectors.get_vecs_by_tokens(examples)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [ ]:
dir(vectors)

In [ ]:
vectors.vectors.size()[0]

183712

In [ ]:
vectors.stoi

In [ ]:
import torch
from torch.nn import Embedding

In [ ]:
embedding = Embedding.from_pretrained(vectors.vectors)

In [ ]:
embedding

Embedding(183712, 300)

In [ ]:
embedding(torch.tensor(0, dtype=int))

In [ ]:
from torchtext.vocab import Vocab
from collections import Counter

In [ ]:
counter = Counter()
tokens = "The dog jumped over the brown fox".split()
counter.update(tokens)
vocab = Vocab(counter, vectors=vectors)
#vocab.set_vectors(vectors.stoi, vectors, vectors.vectors.size()[1])

In [ ]:
dir(vocab)

In [ ]:
vocab['The']

2

In [ ]:
vocab.lookup_indices(['The'])

[2]

In [ ]:
vocab.stoi

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x7f64266025d0>>,
            {'<pad>': 1,
             '<unk>': 0,
             'The': 2,
             'brown': 3,
             'dog': 4,
             'fox': 5,
             'jumped': 6,
             'over': 7,
             'the': 8})

In [ ]:
vocab.vectors[vocab['The']]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
vocab.vectors.get_vecs_by_tokens("The")

AttributeError: ignored

In [ ]:
embedding(torch.tensor(vocab["The"], dtype=int))

tensor([-3.1085e-02, -1.9180e-01, -1.2844e-01, -2.2440e-01,  2.0963e-01,
         4.3290e-02, -4.2737e+00, -2.8835e-02,  1.0796e-01, -6.7202e-01,
         7.5191e-02, -1.8757e-01,  9.0388e-02, -2.1803e-01,  2.5414e-01,
        -1.9365e-01, -7.8324e-02,  8.6168e-02,  3.3886e-01, -4.9365e-02,
         5.4362e-01, -2.1859e-01,  3.8286e-01,  1.3160e-01, -2.8986e-01,
        -5.6643e-01, -4.1744e-01, -2.8723e-01,  1.4621e-01, -6.7876e-02,
        -7.0323e-02, -5.1577e-02,  3.9586e-01, -3.3439e-02,  3.1436e-01,
        -1.0135e-01, -3.3586e-01, -1.1693e-01,  2.9510e-01,  9.8460e-02,
         1.0714e-02,  3.3689e-01, -1.9365e-01, -2.5544e-01, -2.1336e-01,
         2.1083e-03, -7.3646e-02, -4.2126e-01, -4.2583e-02, -3.1212e-01,
        -1.1005e-01, -3.3348e-01,  1.8572e-01, -3.2653e-01, -1.6437e-01,
        -5.6337e-02,  8.8778e-02, -2.9362e-01,  4.4158e-01,  9.8100e-02,
         1.9068e-01, -1.6174e-01,  1.0667e-01, -3.0509e-01,  7.5123e-03,
         4.3102e-01, -9.6605e-02, -1.1779e-01, -3.7

# Load IMBd

In [ ]:
from torchtext.datasets import IMDB
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch
from tqdm.notebook import tqdm

In [ ]:
train_iter, test_iter = IMDB()

aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:03<00:00, 21.3MB/s]


In [ ]:
x_train = []
y_train = []
for label, line in train_iter:
    x_train.append(line)
    y_train.append(label)


x_test = []
y_test = []
for label, line in test_iter:
    x_test.append(line)
    y_test.append(label)

In [ ]:
x_train[:4]

['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, e

In [ ]:
y_train[:4]

['neg', 'neg', 'neg', 'neg']

In [ ]:
x_test[:4]

['I love sci-fi and am willing to put up with a lot. Sci-fi movies/TV are usually underfunded, under-appreciated and misunderstood. I tried to like this, I really did, but it is to good TV sci-fi as Babylon 5 is to Star Trek (the original). Silly prosthetics, cheap cardboard sets, stilted dialogues, CG that doesn\'t match the background, and painfully one-dimensional characters cannot be overcome with a \'sci-fi\' setting. (I\'m sure there are those of you out there who think Babylon 5 is good sci-fi TV. It\'s not. It\'s clichéd and uninspiring.) While US viewers might like emotion and character development, sci-fi is a genre that does not take itself seriously (cf. Star Trek). It may treat important issues, yet not as a serious philosophy. It\'s really difficult to care about the characters here as they are not simply foolish, just missing a spark of life. Their actions and reactions are wooden and predictable, often painful to watch. The makers of Earth KNOW it\'s rubbish as they hav

In [ ]:
y_test[:4]

['neg', 'neg', 'neg', 'neg']

# Get BERT scores

In [ ]:
clf = pipeline('sentiment-analysis', 
               model="distilbert-base-uncased-finetuned-sst-2-english", 
               device=torch.cuda.current_device())

In [ ]:
tokenizer_kwargs = dict(padding=True,
                        truncation=True,
                        max_length=512,
                        return_tensors="pt")

In [ ]:
clf(x_train[:10], **tokenizer_kwargs)

[{'label': 'POSITIVE', 'score': 0.7872869968414307},
 {'label': 'NEGATIVE', 'score': 0.9991909861564636},
 {'label': 'NEGATIVE', 'score': 0.9982178211212158},
 {'label': 'POSITIVE', 'score': 0.8144601583480835},
 {'label': 'NEGATIVE', 'score': 0.9993876814842224},
 {'label': 'NEGATIVE', 'score': 0.9989562630653381},
 {'label': 'NEGATIVE', 'score': 0.9994860291481018},
 {'label': 'NEGATIVE', 'score': 0.996175229549408},
 {'label': 'NEGATIVE', 'score': 0.989343523979187},
 {'label': 'NEGATIVE', 'score': 0.9909104108810425}]

In [ ]:
y_train[:10]

['neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg']

### Run entire dataset set through BERT

In [ ]:
def get_batches(data, batch_size=10):
    out = []
    for i, d in enumerate(data):
        out.append(d)
        if (i + 1) % batch_size == 0:
            yield out
            out = []

In [ ]:
batch_size = 50
num_batches = len(x_train + x_test) / batch_size
yhat = []
for x_batch in tqdm(get_batches(x_train + x_test, batch_size=batch_size), total=num_batches):
    yhat.extend(clf(x_batch, **tokenizer_kwargs))

In [ ]:
bert_scores = pd.DataFrame(yhat)
print(bert_scores.shape)
bert_scores.head()

(50000, 2)


label     score
0  POSITIVE  0.787287
1  NEGATIVE  0.999191
2  NEGATIVE  0.998218
3  POSITIVE  0.814460
4  NEGATIVE  0.999388

Write out to csv

In [ ]:
bert_scores.to_csv('imbd_bert_scores.csv', index_label='id')

# Get BERT review embeddings 

In [ ]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
pt_model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
pt_batch = tokenizer(
    x_train[:10],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="pt"
)

In [ ]:
pt_outputs = pt_model(**pt_batch, output_hidden_states=True)

In [ ]:
pt_outputs

In [ ]:
pt_outputs.hidden_states

(tensor([[[ 0.3549, -0.1386, -0.2253,  ...,  0.1536,  0.0748,  0.1310],
          [ 0.2282,  0.5511, -0.5092,  ...,  0.6421,  0.9541,  0.3192],
          [-2.0722, -0.6960, -0.7317,  ...,  0.0574,  0.2823,  0.6993],
          ...,
          [ 0.3740, -0.0294, -0.0420,  ...,  0.2570, -0.0529,  0.8533],
          [ 0.1270,  0.5198, -0.0711,  ...,  0.3751,  0.1634,  0.4257],
          [-0.0564,  0.1544, -0.1891,  ..., -0.0625, -0.0342,  0.1120]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[-1.3664e-01,  1.8010e-02, -9.8503e-02,  ...,  1.5377e-01,
            5.7496e-02,  8.4130e-02],
          [ 2.4336e-01,  5.0640e-01, -4.7071e-01,  ...,  7.0713e-01,
            7.6154e-01,  1.0730e+00],
          [-1.4912e+00, -5.0866e-01,  6.8742e-02,  ...,  2.2801e-01,
            3.2560e-01,  8.3328e-01],
          ...,
          [ 5.1544e-01,  1.7000e-01, -1.6902e-01,  ...,  4.3245e-01,
           -7.2209e-02,  6.8319e-01],
          [ 6.5775e-04,  3.3590e-02,  1.5539e-01,  ...,  2.3400e

In [ ]:
len(pt_outputs.hidden_states)

7

In [ ]:
for l in pt_outputs.hidden_states:
  print(l.size())

torch.Size([5, 495, 768])
torch.Size([5, 495, 768])
torch.Size([5, 495, 768])
torch.Size([5, 495, 768])
torch.Size([5, 495, 768])
torch.Size([5, 495, 768])
torch.Size([5, 495, 768])


In [ ]:
pt_outputs.hidden_states[-1].size()

torch.Size([1, 363, 768])